version: "3.9"

services:
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "7081:8080"
      - "7080:8000"
    networks:
      - frontend
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  mysql_data:

networks:
  frontend:
    external: true
